//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProject.Models.Entity
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvProjectEntities3 : DbContext
    {
        public CvProjectEntities3()
            : base("name=CvProjectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLABOUT> TBLABOUT { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLITEM> TBLITEM { get; set; }
        public virtual DbSet<TBLMAIN> TBLMAIN { get; set; }
        public virtual DbSet<TBLPROJECTS> TBLPROJECTS { get; set; }
        public virtual DbSet<TBLSKILLS> TBLSKILLS { get; set; }
        public virtual DbSet<TBLUSERS> TBLUSERS { get; set; }
    }
}
