//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTACT
    {
        public int SMID { get; set; }
        public string PHONE { get; set; }
        public string SMLGIT { get; set; }
        public string LINKGIT { get; set; }
        public string SMLLINKED { get; set; }
        public string LINKIN { get; set; }
        public string LMAIL { get; set; }
        public Nullable<int> CITEMID { get; set; }
    
        public virtual TBLITEM TBLITEM { get; set; }
    }
}
