//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLMAIN
    {
        public int MID { get; set; }
        [Required(ErrorMessage = "Ýsim alaný boþ býrakýlamaz")]
        
        public string NAME { get; set; }
        [Required(ErrorMessage = "Açýklama alaný boþ býrakýlamaz")]
        public string DESCRIPTION { get; set; }
        public Nullable<int> M_ACTIVE { get; set; }
    }
}
