//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPROJECTS
    {
        public int PID { get; set; }
        public string JOBS { get; set; }
        public string WORKS { get; set; }
        public Nullable<int> PITEMID { get; set; }
    
        public virtual TBLITEM TBLITEM { get; set; }
    }
}
