//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSKILLS
    {
        public int SID { get; set; }
        public string SKILLS { get; set; }
        public Nullable<int> SITEMID { get; set; }
    
        public virtual TBLITEM TBLITEM { get; set; }
    }
}
